# -*- coding: utf-8 -*-
"""Lists(학생용).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hSmw3Y7Z4K9hEwWskRjaygLUwb2CAC41

<h1>Lists in Python</h1> #내부 값을 바꿀 수 있는게 튜플과 차이

<p><strong>Welcome!</strong> This notebook will teach you about the lists in the Python Programming Language. By the end of this lab, you'll know the basics list operations in Python, including indexing, list operations and copy/clone list.</p>

<h2 id="#dataset">About the Dataset</h2>

Imagine you received album recommendations from your friends and compiled all of the recommandations into a table, with specific information about each album.

The table has one row for each movie and several columns:

- **artist** - Name of the artist
- **album** - Name of the album
- **released_year** - Year the album was released
- **length_min_sec** - Length of the album (hours,minutes,seconds)
- **genre** - Genre of the album
- **music_recording_sales_millions** - Music recording sales (millions in USD)
- **claimed_sales_millions** - Album's claimed sales (millions in USD)
- **date_released** - Date on which the album was released
- **soundtrack** - Indicates if the album is the movie soundtrack (Y) or (N)
- **rating_of_friends** - Indicates the rating from your friends from 1 to 10
<br>
<br>

The dataset can be seen below:

<font size="1">
<table font-size:xx-small style="width:25%">
  <tr>
    <th>Artist</th>
    <th>Album</th>
    <th>Released</th>
    <th>Length</th>
    <th>Genre</th>
    <th>Music recording sales (millions)</th>
    <th>Claimed sales (millions)</th>
    <th>Released</th>
    <th>Soundtrack</th>
    <th>Rating (friends)</th>
  </tr>
  <tr>
    <td>Michael Jackson</td>
    <td>Thriller</td>
    <td>1982</td>
    <td>00:42:19</td>
    <td>Pop, rock, R&B</td>
    <td>46</td>
    <td>65</td>
    <td>30-Nov-82</td>
    <td></td>
    <td>10.0</td>
  </tr>
  <tr>
    <td>AC/DC</td>
    <td>Back in Black</td>
    <td>1980</td>
    <td>00:42:11</td>
    <td>Hard rock</td>
    <td>26.1</td>
    <td>50</td>
    <td>25-Jul-80</td>
    <td></td>
    <td>8.5</td>
  </tr>
    <tr>
    <td>Pink Floyd</td>
    <td>The Dark Side of the Moon</td>
    <td>1973</td>
    <td>00:42:49</td>
    <td>Progressive rock</td>
    <td>24.2</td>
    <td>45</td>
    <td>01-Mar-73</td>
    <td></td>
    <td>9.5</td>
  </tr>
    <tr>
    <td>Whitney Houston</td>
    <td>The Bodyguard</td>
    <td>1992</td>
    <td>00:57:44</td>
    <td>Soundtrack/R&B, soul, pop</td>
    <td>26.1</td>
    <td>50</td>
    <td>25-Jul-80</td>
    <td>Y</td>
    <td>7.0</td>
  </tr>
    <tr>
    <td>Meat Loaf</td>
    <td>Bat Out of Hell</td>
    <td>1977</td>
    <td>00:46:33</td>
    <td>Hard rock, progressive rock</td>
    <td>20.6</td>
    <td>43</td>
    <td>21-Oct-77</td>
    <td></td>
    <td>7.0</td>
  </tr>
    <tr>
    <td>Eagles</td>
    <td>Their Greatest Hits (1971-1975)</td>
    <td>1976</td>
    <td>00:43:08</td>
    <td>Rock, soft rock, folk rock</td>
    <td>32.2</td>
    <td>42</td>
    <td>17-Feb-76</td>
    <td></td>
    <td>9.5</td>
  </tr>
    <tr>
    <td>Bee Gees</td>
    <td>Saturday Night Fever</td>
    <td>1977</td>
    <td>1:15:54</td>
    <td>Disco</td>
    <td>20.6</td>
    <td>40</td>
    <td>15-Nov-77</td>
    <td>Y</td>
    <td>9.0</td>
  </tr>
    <tr>
    <td>Fleetwood Mac</td>
    <td>Rumours</td>
    <td>1977</td>
    <td>00:40:01</td>
    <td>Soft rock</td>
    <td>27.9</td>
    <td>40</td>
    <td>04-Feb-77</td>
    <td></td>
    <td>9.5</td>
  </tr>
</table></font>

<hr>

<h2 id="list">Lists</h2>

<h3 id="index">Indexing</h3>

We are going to take a look at lists in Python. A list is a sequenced collection of different objects such as integers, strings, and other lists as well. The address of each element within a list is called an <b>index</b>. An index is used to access and refer to items within a list.

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/ListsIndex.png" width="1000" />

To create a list, type the list within square brackets <b>[ ]</b>, with your content inside the parenthesis and separated by commas. Let’s try it!
"""

# Create a list

L = ["Michael Jackson", 10.1, 1982] #[] : indexing
L

type(L[2]) #len는 문자열만

"""We can use negative and regular indexing with a list :

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/ListsNeg.png" width="1000" />
"""

# Print the elements on each index

print('the same element using negative and positive indexing:\n Postive:',L[0],
'\n Negative:' , L[-3]  )
print('the same element using negative and positive indexing:\n Postive:',L[1],
'\n Negative:' , L[-2]  )
print('the same element using negative and positive indexing:\n Postive:',L[2],
'\n Negative:' , L[-1]  )

"""<h3 id="content">List Content</h3>

Lists can contain strings, floats, and integers. We can nest other lists, and we can also nest tuples and other data structures. The same indexing conventions apply for nesting:
"""

#Differnece between List and Tuple is List is mutable (changeable) but not tuple

L1 = ["Michael Jackson", 10.1, 1982, [1, 2], ("A", 1)]
print("before L1[0] changed", L1)
L1[0] = "Janet"
print("after L1[0] changed", L1)

Tuple1=("Michael Jackson", 10.1, 1982)
Tuple1
Tuple1[0]="Janet"

"""<h3 id="op">List Operations (함수, 기능, 즉 LIST를 사용하면 쓸 수 있는 무기)</h3>

We can also perform slicing in lists. For example, if we want the last two elements, we use the following command:
"""

# Sample List

L = ["Michael Jackson", 10.1,1982,"MJ",1]
L

"""<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/ListsSlice.png" width="1000">"""

# List slicing

L[3:5]

"""We can use the method <code>extend</code> to add new elements to the list:"""

# Use extend to add elements to list  # 두개의 리스트를 하나의 통합된 리스트

L = [ "Michael Jackson", 10.2]
L.extend(['pop', 10]) #['pop', 10] --> list
L

"""Another similar method is <code>append</code>. If we apply <code>append</code> instead of <code>extend</code>, we add one element to the list:"""

# Use append to add elements to list # 리스트에 걍 뭐든 붙여버림

L = [ "Michael Jackson", 10.2]
L.append(['pop', 10]) #['pop', 10]
L

""" We can also delete an element of a list using the <code>del</code> command:"""

# Delete the element based on the index
A = ['Michael Jackson', 10.2, 'pop', 10, ['a', 'b']]
print('Before change:', A)
del(A[0])
print('After change:', A)

"""We can convert a string to a list using <code>split</code>.  For example, the method <code>split</code> translates every group of characters separated by a space into an element in a list:"""

A = ['Michael Jackson', 10.2, 'pop', 10]

# Split the string, default is by space

what='hard rock'.split()
print(what)
type(what)
what[1]

"""We can use the split function to separate strings on a specific character. We pass the character we would like to split on into the argument, which in this case is a comma.  The result is a list, and each element corresponds to a set of characters that have been separated by a comma:"""

from re import split
# Split the string by comma

Split_string_comma='A,B,C,D'.split(',')
Split_string_comma
type(Split_string_comma)
Split_string_comma[0]

"""<h3 id="co">Copy and Clone List</h3>

When we set one variable <b>B</b> equal to <b>A</b>; both <b>A</b> and <b>B</b> are referencing the same list in memory:
"""

# Copy (copy by reference) the list A

A = ["hard rock", 10, 1.2]
B = A # B = A (같은 곳을 가리킨다 not equal to 같은 값을 두개 따로 가지는 것은 아니다) -->B에게 알려준다.. 너는 인제 A에서 찾아야 해...B = A (assign)


A[0] = "R&B"

print('A:', A) #R&B, 10, 1.2
print('B:', B) #'hard rock, 10, 1.2

"""<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/ListsRef.png" width="1000" align="center">

Initially, the value of the first element in <b>B</b> is set as hard rock. If we change the first element in <b>A</b> to <b>banana</b>, we get an unexpected side effect.  As <b>A</b> and <b>B</b> are referencing the same list, if we change list <b>A</b>, then list <b>B</b> also changes. If we check the first element of <b>B</b> we get banana instead of hard rock:
"""

# Examine the copy by reference

print('B[0]:', B[0])
A[0] = "banana"
print('B[0]:', B[0])

"""You can clone list  **A** by using  the following syntax:"""

# Clone (clone by value) the list A
A = ["hard rock", 10, 1.2]
B = A[:] #A[:]
print(A)
print(B)
A[0] ='R&B'
print(A)
print(B)
#A[0] = "Banana"
#print(B)
#print(A)

"""Variable **B** references a new copy or clone of the original list; this is demonstrated in the following figure:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/ListsVal.gif" width="1000" />

<h2 id="quiz">Quiz on List</h2>

Create a list <code>a_list</code>, with the following elements <code>1</code>, <code>hello</code>, <code>[1,2,3]</code> and <code>True</code>.
"""

# Write your code below and press Shift+Enter to execute

a_list = [1, 'hello', [1,2,3], True]
a_list

"""Double-click <b>here</b> for the solution.

<!-- Your answer is below:
a_list = [1, 'hello', [1, 2, 3] , True]
a_list
-->

Find the value stored at index 1 of <code>a_list</code>.
"""

# Write your code below and press Shift+Enter to execute

a_list[1]

"""Double-click <b>here</b> for the solution.

<!-- Your answer is below:
a_list[1]
-->

Retrieve the elements stored at index 1, 2 and 3 of <code>a_list</code>.
"""

# Write your code below and press Shift+Enter to execute

a_list[1:4]

"""Double-click <b>here</b> for the solution.

<!-- Your answer is below:
a_list[1:4]
-->

Concatenate the following lists <code>A = [1, 'a']</code> and <code>B = [2, 1, 'd']</code>:
"""

# Write your code below and press Shift+Enter to execute

A = [1, 'a']
B = [2, 1, 'd']
A+B

"""Double-click <b>here</b> for the solution.

<!-- Your answer is below:
A = [1, 'a']
B = [2, 1, 'd']
A + B
-->

<hr>
<h2>The last exercise!</h2>
<p>Congratulations, you have completed your first lesson and hands-on lab in Python. However, there is one more thing you need to do. The Data Science community encourages sharing work. The best way to share and showcase your work is to share it on GitHub. By sharing your notebook on GitHub you are not only building your reputation with fellow data scientists, but you can also show it off when applying for a job. Even though this was your first piece of work, it is never too early to start building good habits. Please submit all your exercises to Github & let the traces in our LMS, so for me to access your work.
<hr>

<hr>

<p>Copyright &copy; 2023 RYU HOKYOUNG based on 2018 IBM Developer Skills Network. This notebook and its source code are released under the terms of the <a href="https://cognitiveclass.ai/mit-license/">MIT License</a>.</p>
"""