# -*- coding: utf-8 -*-
"""Dictionaries(학생용).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VT1B2uWuQCNC8XffKfXLFdm94WS8frpP

<h1>Dictionaries in Python</h1>

<p><strong>Welcome!</strong> This notebook will teach you about the dictionaries in the Python Programming Language. By the end of this lab, you'll know the basics dictionary operations in Python, including what it is, and the operations on it.</p>

<h2 id="Dic">Dictionaries</h2>

<h3 id="content">What are Dictionaries?</h3>

A dictionary consists of keys and values. It is helpful to compare a dictionary to a list. Instead of the numerical indexes such as a list, dictionaries have keys. These keys are the keys that are used to access values within a dictionary.

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/DictsList.png" width="650" />

An example of a Dictionary <code>Dict</code>:
"""

# Create the dictionary

Dict = {"key1": 1, "key2": "2", "key3": [3, 3, 3], "key4": (4, 4, 4), 'key5': 5, (0, 1): 6, 1.2: 5}
#{} :
# key1 (키값) --> 1 (정수)
# key2 (키값) --> "2" (문자열)
# key4 (키값) --> (4,4,4) tuple
# 리스트 [] 는 키값이 될 수 없음
# (0,1) tuple 키값 --> 6 (정수)
Dict

"""The keys can be strings:"""

# Access to the value by the key
#Dict[1.2]
#Dict['key5']
#Dict[(0,1)]
Dict["key3"]

Dict

"""Keys can also be any mutable object such as a LIST:"""

# Access to the value by the key

Dict["key3"]="TEST" #다른 값을 넣을 수 있니?
Dict

""" Each key is separated from its value by a colon "<code>:</code>".  Commas separate the items, and the whole dictionary is enclosed in curly braces. An empty dictionary without any items is written with just two curly braces, like this  "<code>{}</code>"."""

# Create a sample dictionary

release_year_dict = {"Thriller": "1982", "Back in Black": "1980", "The Dark Side of the Moon": "1973", "The Bodyguard": "1992", \
                    "Bat Out of Hell": "1977", "Their Greatest Hits (1971-1975)": "1976", \
                    "Saturday Night Fever": "1977", "Rumours": "1977"}
release_year_dict

"""In summary, like a list, a dictionary holds a sequence of elements. Each element is represented by a key and its corresponding value. Dictionaries are created with two curly braces containing keys and values separated by a colon. For every key, there can only be one single value, however,  multiple keys can hold the same value. Keys can only be strings, numbers, or tuples, but values can be any data type.

It is helpful to visualize the dictionary as a table, as in the following image. The first column represents the keys, the second column represents the values.

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/DictsStructure.png" width="650" />

<h3 id="key">Keys</h3>

You can retrieve the values based on the names:
"""

# Get value by keys

release_year_dict['Their Greatest Hits (1971-1975)']

"""This corresponds to:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/DictsKeyOne.png" width="500" />

Similarly for <b>The Bodyguard</b>
"""

# Get value by key

release_year_dict['The Bodyguard']

"""<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%202/Images/DictsKeyTwo.png" width="500" />

Now let you retrieve the keys of the dictionary using the method <code>release_year_dict()</code>:
"""

# Get all the keys in dictionary

release_year_dict.keys()

"""You can retrieve the values using the method  <code>values()</code>:"""

# Get all the values in dictionary

release_year_dict.values()



"""We can add an entry:"""

# Append value with key into dictionary

release_year_dict['Graduation'] = '2007'
release_year_dict

"""We can delete an entry:   """

# Delete entries by key

del(release_year_dict['Thriller'])
del(release_year_dict['Graduation'])
release_year_dict

""" We can verify if an element is in the dictionary:"""

'Thriller' in release_year_dict

del(release_year_dict['Rumours'])

'Rumours' in release_year_dict

'The Bodyguard' in release_year_dict

"""<h2 id="quiz">Quiz on Dictionaries</h2>

<b>You will need this dictionary for the next two questions:</b>
"""

# Question sample dictionary

soundtrack_dic = {"The Bodyguard":"1992", "Saturday Night Fever":"1977"}
soundtrack_dic

"""a) In the dictionary <code>soundtrack_dict</code> what are the keys ?"""

# Write your code below and press Shift+Enter to execute)

soundtrack_dic = {"The Bodyguard":"1992", "Saturday Night Fever":"1977"}
soundtrack_dic

soundtrack_dic.keys()

"""Double-click __here__ for the solution.

<!-- Your answer is below:
soundtrack_dic.keys() # The Keys "The Bodyguard" and "Saturday Night Fever"
-->

b) In the dictionary <code>soundtrack_dict</code> what are the values ?
"""

# Write your code below and press Shift+Enter to execute

soundtrack_dic.values()

"""Double-click __here__ for the solution.

<!-- Your answer is below:
soundtrack_dic.values() # The values are "1992" and "1977"
-->

<hr>

<b>You will need this dictionary for the following questions:</b>

The Albums <b>Back in Black</b>, <b>The Bodyguard</b> and <b>Thriller</b> have the following music recording sales in millions 50, 50 and 65 respectively:

a) Create a dictionary <code>album_sales_dict</code> where the keys are the album name and the sales in millions are the values.
"""

# Write your code below and press Shift+Enter to execute

album_sales_dict = {"The Bodyguard":50, "Back in Black":50, "Thriller":65}
album_sales_dict

"""Double-click __here__ for the solution.

<!-- Your answer is below:
album_sales_dict = {"The Bodyguard":50, "Back in Black":50, "Thriller":65}
-->

b) Use the dictionary to find the total sales of <b>Thriller</b>:
"""

# Write your code below and press Shift+Enter to execute

album_sales_dict["Thriller"]

"""Double-click __here__ for the solution.

<!-- Your answer is below:
album_sales_dict["Thriller"]
-->

c) Find the names of the albums from the dictionary using the method <code>keys</code>:
"""

# Write your code below and press Shift+Enter to execute

album_sales_dict.keys()

"""Double-click __here__ for the solution.

<!-- Your answer is below:
album_sales_dict.keys()
-->

d) Find the names of the recording sales from the dictionary using the method <code>values</code>:
"""

# Write your code below and press Shift+Enter to execute

album_sales_dict.values()

"""Double-click __here__ for the solution.

<!-- Your answer is below:
album_sales_dict.values()
-->

<hr>
<h2>The last exercise!</h2>
<p>Congratulations, you have completed your first lesson and hands-on lab in Python. However, there is one more thing you need to do. The Data Science community encourages sharing work. The best way to share and showcase your work is to share it on GitHub. By sharing your notebook on GitHub you are not only building your reputation with fellow data scientists, but you can also show it off when applying for a job. Even though this was your first piece of work, it is never too early to start building good habits. Please submit all your exercises to Github & let the traces in our LMS, so for me to access your work.

<hr>

<p>Copyright &copy; 2023 RYU HOKYOUNG based on 2018 IBM Developer Skills Network. This notebook and its source code are released under the terms of the <a href="https://cognitiveclass.ai/mit-license/">MIT License</a>.</p>
"""