# -*- coding: utf-8 -*-
"""Loops(학생용).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10PYEhtaKKjYeyZEj70Zi2WyKOP-VDU9O

<h1>Loops in Python (반복문) </h1>

<p><strong>Welcome!</strong> This notebook will teach you about the loops in the Python Programming Language. By the end of this lab, you'll know how to use the loop statements in Python, including for loop, and while loop.</p>

<h2 id="loop">Loops</h2>

<h3 id="range">Range</h3>

Sometimes, you might want to repeat a given operation many times. Repeated executions like this are performed by <b>loops</b>. We will look at two types of loops, <code>for</code> loops and <code>while</code> loops.

Before we discuss loops lets discuss the <code>range</code> object. It is helpful to think of the range object as an ordered list. For now, let's look at the simplest case. If we would like to generate a sequence that contains three elements ordered from 0 to 2 we simply use the following command:
"""

# Use the range ([0, 1, 2])

test=range(3)
test

"""<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%203/Images/LoopsRange.png" width="300" />

<h3 id="for">What is <code>for</code> loop?</h3>

The <code>for</code> loop enables you to execute a code block multiple times. For example, you would use this if you would like to print out every element in a list.    
Let's try to use a <code>for</code> loop to print all the years presented in the list <code>dates</code>:

This can be done as follows:
"""

# For loop example

dates = [1982,1980,1973] #List[0] =1982
N = len(dates) #3

for i in range(N): #range(3) = [0, 1, 2] list --> i는 list에 있는 첫번째 값인 0, 그 다음에는 두번째 값인 1, 그 다음에는 세번째 값인 2
    print(dates[i]) # i=0 , i =1 , i =2   --> dates[0] = 1982, dates[1] = 1980, dates[2] =1973

"""The code in the indent is executed <code>N</code> times, each time the value of <code>i</code> is increased by 1 for every execution. The statement executed is to <code>print</code> out the value in the list at index <code>i</code> as shown here:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%203/Images/LoopsForRange.gif" width="800" />

In this example we can print out a sequence of numbers from 0 to 7:
"""

# Example of for loop

for i in range(0, 8): #range(8)
    print("i is equal to", i)

"""In Python we can directly access the elements in the list as follows:"""

# Exmaple of for loop, loop through list

for year in dates:  #이것을 가장 자주 사용한다.
    print(year)

"""For each iteration, the value of the variable <code>years</code> behaves like the value of <code>dates[i]</code> in the  first example:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%203/Images/LoopsForList.gif" width="800">

We can change the elements in a list:
"""

# Use for loop to change the elements in list

squares = ['red', 'yellow', 'green', 'purple', 'blue']

for i in range(0, 5):
    print("Before square ", i, 'is',  squares[i])
    squares[i] = 'weight'
    print("After square ", i, 'is',  squares[i])

squares

squares = ['red', 'yellow', 'green', 'purple', 'blue']

for i in squares:
  print("Before square is: ", i)
for i in range(0,5):
  squares[i] = i* "what the heck!"
  print(squares[i])

"""<h3 id="while">What is <code>while</code> loop?</h3> 조건이 만족될 때까지 계속 수행

As you can see, the <code>for</code> loop is used for a controlled flow of repetition. However, what if we don't know when we want to stop the loop? What if we want to keep executing a code block until a certain condition is met? The <code>while</code> loop exists as a tool for repeated execution based on a condition. The code block will keep being executed until the given logical condition returns a **False** boolean value.

Let’s say we would like to iterate through list <code>dates</code> and stop at the year 1973, then print out the number of iterations. This can be done with the following block of code:
"""

# While Loop Example

dates = [1982, 1980, 1973, 2000]

i = 0
year = 0

while(year != 2000):
    year = dates[i] #1982, 1980, 1973, 2000
    i = i + 1 #i =1, 2, 3, 4
    print(year) #1982, 1980, 1973, 2000

print("It took ", i ,"repetitions to get out of loop.")

"""A while loop iterates merely until the condition in the argument is not  met, as shown in the following figure:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%203/Images/LoopsWhile.gif" width="650" />

<hr>

<h2 id="quiz">Quiz on Loops</h2>

Write a <code>for</code> loop the prints out all the element between <b>-5</b> and <b>5</b> using the range function.
"""

# Write your code below and press Shift+Enter to execute

for i in range(-5, 6):
  print(i)

"""Double-click __here__ for the solution.
<!--
for i in range(-5, 6):
    print(i)
-->

Print the elements of the following list:
<code>Genres=[ 'rock', 'R&B', 'Soundtrack', 'R&B', 'soul', 'pop']</code>
Make sure you follow Python conventions.
"""

# Write your code below and press Shift+Enter to execute

Genres=[ 'rock', 'R&B', 'Soundtrack', 'R&B', 'soul', 'pop']

for Genre in Genres:
  print(Genre)

"""Double-click __here__ for the solution.
<!--
Genres = ['rock', 'R&B', 'Soundtrack', 'R&B', 'soul', 'pop']
for Genre in Genres:
    print(Genre)
-->

<hr>

Write a for loop that prints out the following list: <code>squares=['red', 'yellow', 'green', 'purple', 'blue']</code>
"""

# Write your code below and press Shift+Enter to execute

squares=['red', 'yellow', 'green', 'purple', 'blue']
for i in squares:
  print(i)

"""Double-click __here__ for the solution.
<!--
squares=['red', 'yellow', 'green', 'purple', 'blue']
for square in squares:
    print(square)
 -->

<hr>

Write a while loop to display the values of the Rating of an album playlist stored in the list <code>PlayListRatings</code>. If the score is less than 6, exit the loop. The list <code>PlayListRatings</code> is given by: <code>PlayListRatings = [10, 9.5, 10, 8, 7.5, 5, 10, 10]</code>
"""

# Write your code below and press Shift+Enter to execute

PlayListRatings = [10, 9.5, 10, 8, 7.5, 5, 10, 10]
i = 1
Rating = PlayListRatings[0]
while(Rating >= 6):
    print(Rating)
    Rating = PlayListRatings[i]
    i = i + 1

"""Double-click __here__ for the solution.
<!--
PlayListRatings = [10, 9.5, 10, 8, 7.5, 5, 10, 10]
i = 1
Rating = PlayListRatings[0]
while(Rating >= 6):
    print(Rating)
    Rating = PlayListRatings[i]
    i = i + 1
 -->

<hr>

Write a while loop to copy the strings <code>'orange'</code> of the list <code>squares</code> to the list <code>new_squares</code>. Stop and exit the loop if the value on the list is not <code>'orange'</code>:
"""

# Write your code below and press Shift+Enter to execute

squares = ['orange', 'orange', 'purple', 'blue ', 'orange']
new_squares = []

squares = ['orange', 'orange', 'purple', 'blue ', 'orange']
new_squares = []
i = 0
while(squares[i] == 'orange'):
    new_squares.append(squares[i])
    i = i + 1
print (new_squares)

"""Double-click __here__ for the solution.
<!--
squares = ['orange', 'orange', 'purple', 'blue ', 'orange']
new_squares = []
i = 0
while(squares[i] == 'orange'):
    new_squares.append(squares[i])
    i = i + 1
print (new_squares)
 -->

<hr>
<h2>The last exercise!</h2>
<p>Congratulations, you have completed your first lesson and hands-on lab in Python. However, there is one more thing you need to do. The Data Science community encourages sharing work. The best way to share and showcase your work is to share it on GitHub. By sharing your notebook on GitHub you are not only building your reputation with fellow data scientists, but you can also show it off when applying for a job. Even though this was your first piece of work, it is never too early to start building good habits. Please submit all your exercises to Github & let the traces in our LMS, so for me to access your work.
<hr>

<hr>

<p>Copyright &copy; 2023 RYU HOKYOUNG based on 2018 IBM Developer Skills Network. This notebook and its source code are released under the terms of the <a href="https://cognitiveclass.ai/mit-license/">MIT License</a>.</p>
"""