# -*- coding: utf-8 -*-
"""ReadFile(학생용).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-szKnZSMMZT7anhHnI2fd_bKMPG5bg8e

<h1>Reading Files Python</h1>

<p><strong>Welcome!</strong> This notebook will teach you about reading the text file in the Python Programming Language. By the end of this lab, you'll know how to read text files.</p>

<h2 id="download">Download Data</h2>
"""

#or use GDrive mounting method #나의 구글드라이브에 접근할 수 있는 권한을 부여하는 것 #기본 정지 작업 왜? 내가 가지고 있는 구글드라이브에서 파일 입출력을 하기 위해서
from google.colab import drive
drive.mount('/content/gdrive')

"""<hr>

<h2 id="read">Reading Text Files</h2>

One way to read or write a file in Python is to use the built-in <code>open</code> function. The <code>open</code> function provides a <b>File object</b> that contains the methods and attributes you need in order to read, save, and manipulate the file. In this notebook, we will only cover <b>.txt</b> files. The first parameter you need is the file path and the file name. An example is shown as follow:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%204/Images/ReadOpen.png" width="500" />

The mode argument is optional and the default value is <b>r</b>. In this notebook we only cover two modes:
<ul>
    <li><b>r</b> Read mode for reading files </li>
    <li><b>w</b> Write mode for writing files</li>
</ul>

For the next example, we will use the text file <b>Example1.txt</b>. The file is shown as follow:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%204/Images/ReadFile.png" width="200" />

We read the file:
"""

# Read the Example1.txt

example1 = "/content/gdrive/My Drive/Colab Notebooks/example1.txt"
file1 = open(example1, "r") #"r"는 example1 객체를 읽을 수 있는 상태로 만들자.

"""We can view the attributes of the file.

The name of the file:
"""

# Print the path of file

file1.name

""" The mode the file object is in:"""

# Print the mode of file, either 'r' or 'w'

file1.mode

"""We can read the file and assign it to a variable :"""

# Read the file

FileContent = file1.read()
FileContent

"""The <b>\n</b> means that there is a new line.

We can print the file:
"""

# Print the file with '\n' as a new line

print(FileContent)

"""The file is of type string:"""

# Type of file content

type(FileContent)

""" We must close the file object:"""

# Close file after finish

file1.close()

"""<hr>

<h2 id="better">A Better Way to Open a File</h2>

Using the <code>with</code> statement is better practice, it automatically closes the file even if the code encounters an exception. The code will run everything in the indent block then close the file object.
"""

# Open file using with

with open(example1, "r") as file1:
    FileContent = file1.read()
    print(FileContent)

"""The file object is closed, you can verify it by running the following cell:  """

# Verify if the file is closed

file1.closed

""" We can see the info in the file:"""

# See the content of file

print(FileContent)

"""The syntax is a little confusing as the file object is after the <code>as</code> statement. We also don’t explicitly close the file. Therefore we summarize the steps in a figure:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%204/Images/ReadWith.png" width="500" />

We don’t have to read the entire file, for example, we can read the first 4 characters by entering three as a parameter to the method **.read()**:
"""

# Read first four characters

with open(example1, "r") as file1:
    print(file1.read(4))

"""Once the method <code>.read(4)</code> is called the first 4 characters are called. If we call the method again, the next 4 characters are called. The output for the following cell will demonstrate the process for different inputs to the method <code>read()</code>:"""

# Read certain amount of characters

with open(example1, "r") as file1:
    print(file1.read(4))
    print(file1.read(4))
    print(file1.read(7))
    print(file1.read(15))

"""The process is illustrated in the below figure, and each color represents the part of the file read after the method <code>read()</code> is called:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%204/Images/ReadChar.png" width="500" />

Here is an example using the same file, but instead we read 16, 5, and then 9 characters at a time:
"""

# Read certain amount of characters

with open(example1, "r") as file1:
    print(file1.read(16))
    print(file1.read(5))
    print(file1.read(9))

"""We can also read one line of the file at a time using the method <code>readline()</code>:"""

# Read one line

with open(example1, "r") as file1:
    print("first line: " + file1.readline())
    print("second line: " + file1.readline())
    print("third line: " + file1.readline())

""" We can use a loop to iterate through each line:

"""

# Iterate through the lines

with open(example1,"r") as file1:
        i = 0;
        for line in file1:
            print("Iteration", str(i), ": ", line)
            i = i + 1;

"""We can use the method <code>readlines()</code> to save the text file to a list:"""

# Read all lines and save as a list --> 자주 사용함

with open(example1, "r") as file1:
    FileasList = file1.readlines()

""" Each element of the list corresponds to a line of text:"""

# Print the first line

FileasList[0]

# Print the second line

FileasList[1]

# Print the third line

FileasList[2]

FileasList[3]

FileasList[4]

"""<hr>
<h2>The last exercise!</h2>
<p>Congratulations, you have completed your first lesson and hands-on lab in Python. However, there is one more thing you need to do. The Data Science community encourages sharing work. The best way to share and showcase your work is to share it on GitHub. By sharing your notebook on GitHub you are not only building your reputation with fellow data scientists, but you can also show it off when applying for a job. Even though this was your first piece of work, it is never too early to start building good habits. Please submit all your exercises to Github & let the traces in our LMS, so for me to access your work
<hr>

<hr>

<p>Copyright &copy; 2023 RYU HOKYOUNG based on 2018 IBM Developer Skills Network. This notebook and its source code are released under the terms of the <a href="https://cognitiveclass.ai/mit-license/">MIT License</a>.</p>
"""